/// Flutter icons FlutterCoffeeLoginUI
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterCoffeeLoginUI
///      fonts:
///       - asset: fonts/FlutterCoffeeLoginUI.ttf
///
///
///
import 'package:flutter/widgets.dart';

class FlutterCoffeeLoginUI {
  FlutterCoffeeLoginUI._();

  static const _kFontFam = 'FlutterCoffeeLoginUI';
  static const String _kFontPkg = null;

  static const IconData google =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
